version: '2.0'
services:
  config:
    image: "busjadev/tracy-config-${TRACY_ENV}"
    build:
      context: ./config
      args:
      - ALPINE_LINUX_IMAGE=${ALPINE_LINUX_IMAGE}
  assets:
    image: "busjadev/tracy-assets-${TRACY_ENV}"
    build:
      context: ./assets
      args:
      - ALPINE_LINUX_IMAGE=${ALPINE_LINUX_IMAGE}
  consul:
    image: "${CONSUL_IMAGE}"
    ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 8600:8600
     - 8600:8600/udp
    command: "${CONSUL_COMMAND}"
  registrator:
    image: "${REGISTRATOR_IMAGE}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "${REGISTRATOR_COMMAND}"
    links:
      - consul
    environment:
      - SERVICE_NAME=registrator
    depends_on:
      - consul
    restart: always
  nginx:
    image: "busjadev/tracy-nginx-${TRACY_ENV}"
    build:
      context: ./nginx
      args:
      - UBUNTU_LINUX_IMAGE=${UBUNTU_LINUX_IMAGE}
      - CONSUL_TEMPLATE_URI=${CONSUL_TEMPLATE_URI}
    ports:
     - 80:80
     - 443:443
    volumes_from:
      - config
    environment:
      - SERVICE_NAME=nginx
    restart: always
  webhook:
    image: "busjadev/tracy-webhook-${TRACY_ENV}"
    build:
      context: ./webhook
      args:
      - UBUNTU_LINUX_IMAGE=${UBUNTU_LINUX_IMAGE}
    ports:
      - 7000
    volumes_from:
      - assets
    environment:
      - SERVICE_NAME=webhook
