version: '2.0'
services:
  config:
    image: "busjadev/tracy-config-${TRACY_ENV}"
    build:
      context: ./config
      args:
      - ALPINE_LINUX_IMAGE=${ALPINE_LINUX_IMAGE}
  consul:
    image: "${CONSUL_IMAGE}"
    ports:
     - 8300:8300
     - 8301:8301/tcp
     - 8301:8301/udp
     - 8302:8302/tcp
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 8600:8600/tcp
     - 8600:8600/udp
    command: "${CONSUL_COMMAND}"
  registrator:
    image: "${REGISTRATOR_IMAGE}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip=172.18.0.1 -tags=registered consul://172.18.0.1:8500
    links:
      - consul
    environment:
      - SERVICE_NAME=registrator
    depends_on:
      - consul
    restart: always
  nginx:
    image: "busjadev/tracy-nginx-${TRACY_ENV}"
    build:
      context: ./nginx
      args:
      - UBUNTU_LINUX_IMAGE=${UBUNTU_LINUX_IMAGE}
      - CONSUL_TEMPLATE_URI=${CONSUL_TEMPLATE_URI}
    ports:
     - 80:80
     - 443:443
    volumes_from:
      - config
    environment:
      - SERVICE_NAME=nginx
    restart: always
  webhook:
    image: "busjadev/tracy-webhook-${TRACY_ENV}"
    build:
      context: ./webhook
      args:
      - UBUNTU_LINUX_IMAGE=${UBUNTU_LINUX_IMAGE}
    ports:
      - 7000
    environment:
      - SERVICE_NAME=webhook
#    healthcheck:
#      test: "curl --fail http://localhost:7000/ || exit 1"
#      interval: 30s
#      timeout: 10s
#      retries: 1
