version: '2.0'
services:
  config:
    image: "busjadev/tracy-config-${TRACY_ENV}"
    build:
      context: ./config
      args:
      - ALPINE_LINUX_IMAGE=${ALPINE_LINUX_IMAGE}
  consul:
    image: "${CONSUL_IMAGE}"
    ports:
     - 8400:8400
     - 8500:8500
     - 8500:8500/udp
    command: "${CONSUL_COMMAND}"
  registrator:
    image: "${REGISTRATOR_IMAGE}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "${REGISTRATOR_COMMAND}"
    links:
      - consul
    environment:
      - SERVICE_NAME=registrator
    restart: always
  nginx-consul:
    image: "${NGINX_IMAGE}"
    ports:
     - 80:80
     - 443:443
    volumes_from:
      - config
    environment:
      - SERVICE_NAME=nginx-consul
  webhook:
    image: "busjadev/tracy-webhook-${TRACY_ENV}"
    build:
      context: ./webhook
      args:
      - UBUNTU_LINUX_IMAGE=${UBUNTU_LINUX_IMAGE}
    ports:
      - 7000
    environment:
      - SERVICE_NAME=webhook
