environment:
  default: &default
    UBUNTU_LINUX_IMAGE: ubuntu:16.04
    ALPINE_LINUX_IMAGE: alpine:latest
    CONSUL_IMAGE: consul:latest
    REGISTRATOR_IMAGE: gliderlabs/registrator:latest
    CONSUL_TEMPLATE_URI: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
  osx:
    <<: *default
  odroid:
    <<: *default
    UBUNTU_LINUX_IMAGE: armhf/ubuntu:16.04
    ALPINE_LINUX_IMAGE: armhf/alpine:latest
    CONSUL_IMAGE: hypriot/rpi-consul
    REGISTRATOR_IMAGE: hypriot/rpi-registrator
    CONSUL_TEMPLATE_URI: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_arm.zip
