environment:
  default: &default
    UBUNTU_LINUX_IMAGE: ubuntu:16.04
    ALPINE_LINUX_IMAGE: alpine
    REGISTRATOR_IMAGE: gliderlabs/registrator
    CONSUL_IMAGE: consul
    CONSUL_TEMPLATE_URI: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
  linux:
    <<: *default
    CONSUL_COMMAND: agent -data-dir=/tmp/consul -server -client 0.0.0.0 -ui -bootstrap -advertise=linux
    REGISTRATOR_COMMAND: -ip=linux -tags=registered consul://linux:8500
  osx:
    <<: *default
    REGISTRATOR_COMMAND: -ip=osx -tags=registered consul://linux:8500
  odroid:
    <<: *default
    UBUNTU_LINUX_IMAGE: armhf/ubuntu:16.04
    ALPINE_LINUX_IMAGE: armhf/alpine
    CONSUL_IMAGE: hypriot/rpi-consul
    CONSUL_TEMPLATE_URI: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_arm.zip
    REGISTRATOR_IMAGE: hypriot/rpi-registrator
    REGISTRATOR_COMMAND: -ip=odroid -tags=registered consul://linux:8500
services:
  linux:
  - config
  - consul
  - nginx
  - assets
  - webhook
  - registrator
  osx:
  - assets
  - webhook
  - registrator
  odroid:
  - assets
  - webhook
  - registrator
