FROM alpine
MAINTAINER busja.dev@gmail.com

VOLUME /etc/consul-template/templates
VOLUME /etc/consul-template/conf

COPY consul/conf/* /etc/consul-template/conf/
COPY consul/templates/* /etc/consul-template/templates/

CMD tail -f /dev/null
